export enum ExternalProvider {
  None = 'None',
  Google = 'Google',
  Slack = 'Slack',
  Facebook = 'Facebook',
  Github = 'Github',
  Gitlab = 'Gitlab',
  Twitter = 'Twitter',
  Heroku = 'Heroku',
  Instagram = 'Instagram',
  Crashlytics = 'Crashlytics',
  Fitbit = 'Fitbit',
  Foursquare = 'Foursquare',
  Magento = 'Magento',
  Mailgun = 'Mailgun',
  NewRelic = 'NewRelic',
  NPM = 'NPM',
  Paypal = 'Paypal',
  Square = 'Square',
  Stripe = 'Stripe',
  Twilio = 'Twilio',
  Teams = 'Teams',
  Aws = 'Aws',
  Hashicorp = 'Hashicorp',
}
